export const sampleProducts = [
	{
		id: 1,
		title: "Asics Gel-Nimbus 23",
		price: 150,
		image: "https://via.placeholder.com/300x300?text=Asics+Gel-Nimbus+23",
		description: "Premium running shoes with excellent cushioning.",
		category: "sneakers",
		colors: ["Black", "Blue", "Red"],
		sizes: ["8", "9", "10", "11", "12"],
		rating: 4.5,
		reviews: 150,
		releaseDate: "2023-03-15",
		onSale: false,
		brand: "Asics",
	},
	{
		id: 2,
		title: "Asics GT-2000 9",
		price: 120,
		image: "https://via.placeholder.com/300x300?text=Asics+GT-2000+9",
		description: "Stable and comfortable running shoes for daily training.",
		category: "sneakers",
		colors: ["Black", "Grey", "White"],
		sizes: ["8", "9", "10", "11", "12"],
		rating: 4.2,
		reviews: 200,
		releaseDate: "2023-02-20",
		onSale: true,
		brand: "Asics",
	},
	{
		id: 3,
		title: "Nike Air Zoom Pegasus 38",
		price: 120,
		image: "https://via.placeholder.com/300x300?text=Nike+Air+Zoom+Pegasus+38",
		description: "Versatile running shoes with responsive cushioning.",
		category: "sneakers",
		colors: ["Black", "Blue", "Green"],
		sizes: ["8", "9", "10", "11", "12"],
		rating: 4.8,
		reviews: 100,
		releaseDate: "2023-04-10",
		onSale: false,
		brand: "Nike",
	},
	{
		id: 4,
		title: "Nike React Infinity Run Flyknit 2",
		price: 160,
		image: "https://via.placeholder.com/300x300?text=Nike+React+Infinity+Run+2",
		description: "Designed to help reduce injury with a smooth ride.",
		category: "sneakers",
		colors: ["Black", "Grey", "White"],
		sizes: ["8", "9", "10", "11", "12"],
		rating: 4.6,
		reviews: 180,
		releaseDate: "2023-01-25",
		onSale: true,
		brand: "Nike",
	},
	{
		id: 5,
		title: "Adidas Ultraboost 21",
		price: 180,
		image: "https://via.placeholder.com/300x300?text=Adidas+Ultraboost+21",
		description: "High-performance running shoes with energy return.",
		category: "sneakers",
		colors: ["Black", "White", "Blue"],
		sizes: ["8", "9", "10", "11", "12"],
		rating: 4.7,
		reviews: 120,
		releaseDate: "2023-05-01",
		onSale: false,
		brand: "Adidas",
	},
	{
		id: 6,
		title: "Adidas Supernova",
		price: 100,
		image: "https://via.placeholder.com/300x300?text=Adidas+Supernova",
		description: "Comfortable and responsive shoes for long runs.",
		category: "sneakers",
		colors: ["Black", "Grey", "Red"],
		sizes: ["8", "9", "10", "11", "12"],
		rating: 4.3,
		reviews: 250,
		releaseDate: "2023-02-10",
		onSale: true,
		brand: "Adidas",
	},
	{
		id: 7,
		title: "Liverpool Home Jersey 21/22",
		price: 90,
		image: "https://via.placeholder.com/300x300?text=Liverpool+Home+Jersey",
		description: "Official Liverpool FC home jersey for the 21/22 season.",
		category: "jerseys",
		colors: ["Red"],
		sizes: ["S", "M", "L", "XL", "XXL"],
		rating: 4.9,
		reviews: 80,
		releaseDate: "2022-08-01",
		onSale: false,
		brand: "Liverpool",
	},
	{
		id: 8,
		title: "Liverpool Away Jersey 21/22",
		price: 90,
		image: "https://via.placeholder.com/300x300?text=Liverpool+Away+Jersey",
		description: "Official Liverpool FC away jersey for the 21/22 season.",
		category: "jerseys",
		colors: ["White"],
		sizes: ["S", "M", "L", "XL", "XXL"],
		rating: 4.6,
		reviews: 110,
		releaseDate: "2022-09-15",
		onSale: true,
		brand: "Liverpool",
	},
	{
		id: 9,
		title: "Yeezy Boost 350 V2",
		price: 220,
		image: "https://via.placeholder.com/300x300?text=Yeezy+Boost+350+V2",
		description: "Iconic Yeezy design with Boost technology.",
		category: "sneakers",
		colors: ["Black", "White", "Grey"],
		sizes: ["8", "9", "10", "11", "12"],
		rating: 4.9,
		reviews: 100,
		releaseDate: "2023-06-20",
		onSale: false,
		brand: "Yeezy",
	},
	{
		id: 10,
		title: "Yeezy Foam Runner",
		price: 80,
		image: "https://via.placeholder.com/300x300?text=Yeezy+Foam+Runner",
		description: "Unique and futuristic Yeezy design.",
		category: "sneakers",
		colors: ["Black", "White", "Brown"],
		sizes: ["S", "M", "L", "XL"],
		rating: 4.4,
		reviews: 150,
		releaseDate: "2023-05-05",
		onSale: true,
		brand: "Yeezy",
	},
	{
		id: 11,
		title: "Nike Mercurial Vapor 14 Elite",
		price: 250,
		image: "https://via.placeholder.com/300x300?text=Nike+Mercurial+Vapor+14",
		description: "High-end soccer cleats for speed and agility.",
		category: "sneakers",
		colors: ["Black", "White", "Orange"],
		sizes: ["7", "8", "9", "10", "11"],
		rating: 4.7,
		reviews: 90,
		releaseDate: "2023-03-22",
		onSale: false,
		brand: "Nike",
	},
	{
		id: 12,
		title: "Adidas Predator Freak.1",
		price: 280,
		image: "https://via.placeholder.com/300x300?text=Adidas+Predator+Freak.1",
		description: "Advanced soccer cleats for ultimate control.",
		category: "sneakers",
		colors: ["Black", "Red", "White"],
		sizes: ["7", "8", "9", "10", "11"],
		rating: 4.8,
		reviews: 70,
		releaseDate: "2023-04-05",
		onSale: true,
		brand: "Adidas",
	},
	{
		id: 13,
		title: "Asics Gel-Kayano 28",
		price: 160,
		image: "https://via.placeholder.com/300x300?text=Asics+Gel-Kayano+28",
		description: "Premium stability running shoes for overpronators.",
		category: "sneakers",
		colors: ["Black", "Blue", "Grey"],
		sizes: ["8", "9", "10", "11", "12"],
		rating: 4.6,
		reviews: 130,
		releaseDate: "2023-01-10",
		onSale: false,
		brand: "Asics",
	},
	{
		id: 14,
		title: "Nike Phantom GT Elite",
		price: 250,
		image: "https://via.placeholder.com/300x300?text=Nike+Phantom+GT+Elite",
		description: "Top-tier soccer cleats for precise touch and control.",
		category: "sneakers",
		colors: ["Black", "White", "Volt"],
		sizes: ["7", "8", "9", "10", "11"],
		rating: 4.9,
		reviews: 60,
		releaseDate: "2023-02-28",
		onSale: true,
		brand: "Nike",
	},
	{
		id: 15,
		title: "Adidas X Speedflow.1",
		price: 250,
		image: "https://via.placeholder.com/300x300?text=Adidas+X+Speedflow.1",
		description: "Lightweight soccer cleats designed for speed.",
		category: "sneakers",
		colors: ["Black", "Red", "White"],
		sizes: ["7", "8", "9", "10", "11"],
		rating: 4.7,
		reviews: 100,
		releaseDate: "2023-03-01",
		onSale: false,
		brand: "Adidas",
	},
	{
		id: 16,
		title: "Liverpool Third Jersey 21/22",
		price: 90,
		image: "https://via.placeholder.com/300x300?text=Liverpool+Third+Jersey",
		description: "Official Liverpool FC third jersey for the 21/22 season.",
		category: "jerseys",
		colors: ["Green"],
		sizes: ["S", "M", "L", "XL", "XXL"],
		rating: 4.5,
		reviews: 75,
		releaseDate: "2022-10-20",
		onSale: true,
		brand: "Liverpool",
	},
	{
		id: 17,
		title: "Yeezy 700 V3",
		price: 200,
		image: "https://via.placeholder.com/300x300?text=Yeezy+700+V3",
		description: "Futuristic Yeezy design with unique aesthetics.",
		category: "sneakers",
		colors: ["Black", "Grey", "Blue"],
		sizes: ["8", "9", "10", "11", "12"],
		rating: 4.6,
		reviews: 125,
		releaseDate: "2023-04-20",
		onSale: false,
		brand: "Yeezy",
	},
	{
		id: 18,
		title: "Nike Air Max 90",
		price: 120,
		image: "https://via.placeholder.com/300x300?text=Nike+Air+Max+90",
		description: "Classic Nike sneakers with timeless style.",
		category: "sneakers",
		colors: ["White", "Black", "Grey"],
		sizes: ["8", "9", "10", "11", "12"],
		rating: 4.4,
		reviews: 220,
		releaseDate: "2023-01-01",
		onSale: true,
		brand: "Nike",
	},
	{
		id: 19,
		title: "Adidas Stan Smith",
		price: 80,
		image: "https://via.placeholder.com/300x300?text=Adidas+Stan+Smith",
		description: "Iconic tennis-inspired sneakers for everyday wear.",
		category: "sneakers",
		colors: ["White", "Black", "Green"],
		sizes: ["8", "9", "10", "11", "12"],
		rating: 4.7,
		reviews: 180,
		releaseDate: "2023-02-01",
		onSale: false,
		brand: "Adidas",
	},
	{
		id: 20,
		title: "Asics Gel-Cumulus 23",
		price: 120,
		image: "https://via.placeholder.com/300x300?text=Asics+Gel-Cumulus+23",
		description: "Comfortable neutral running shoes for daily use.",
		category: "sneakers",
		colors: ["Black", "White", "Blue"],
		sizes: ["8", "9", "10", "11", "12"],
		rating: 4.5,
		reviews: 160,
		releaseDate: "2023-03-05",
		onSale: true,
		brand: "Asics",
	},
];

export function getFeaturedProducts(products, count = 4) {
	return products.sort((a, b) => b.rating - a.rating).slice(0, count);
}

export function getNewArrivals(products, count = 4) {
	return products
		.sort((a, b) => new Date(b.releaseDate) - new Date(a.releaseDate))
		.slice(0, count);
}

export function getRecommendedProducts(products, preferences, count = 4) {
	return products
		.filter((product) =>
			preferences.some(
				(pref) => product.category === pref || product.brand === pref
			)
		)
		.sort(() => Math.random() - 0.5)
		.slice(0, count);
}

export function getPromotions(products, count = 4) {
	return products
		.filter((product) => product.onSale)
		.sort(() => Math.random() - 0.5)
		.slice(0, count);
}
